/**
 * The Apollonian gasket, generated by the one equation that decides it.
 *
 * Four circles that are each tangent to the other three are a Descartes quadruple, and
 * their bends — a bend being one over the radius, taken negative for the circle that
 * holds the others inside it — satisfy
 *
 *   (k1 + k2 + k3 + k4)^2 = 2 (k1^2 + k2^2 + k3^2 + k4^2).
 *
 * Read as a quadratic in k4 it has two roots, which are the two circles that fit in the
 * space left by the other three. Knowing one of them gives the other by Vieta:
 *
 *   k4' = 2 (k1 + k2 + k3) - k4,
 *
 * and the same relation with each bend multiplied by its own centre gives that circle's
 * centre. So a quadruple has four neighbouring quadruples, one for each member swapped
 * out, and the packing is what comes of following all of them. Nothing is chosen and
 * nothing is fitted: every gap left by three mutually tangent circles admits exactly one
 * more, and where it goes and how big it is were settled by the three around it.
 *
 * The bends this one starts from are whole numbers satisfying the equation, and because
 * the recurrence only ever adds and doubles, every bend it reaches is a whole number too:
 * the figure turns out to be made of integers.
 */

/**
 * The bends the packing starts from. They are whole numbers satisfying Descartes's
 * relation — 34 squared is 1156, and so is twice 36 + 121 + 196 + 225 — and because the
 * recurrence only adds and doubles, every bend the packing reaches is a whole number too.
 * The outer circle's bend is negative because it holds the others inside it.
 *
 * Three inner circles of comparable size rather than two large ones and a small: each of
 * the curvilinear triangles they leave is wide enough to show its own cascade, so the
 * self-similarity is in the picture and not only in the arithmetic.
 */
export const ROOT_BENDS = [-6, 11, 14, 15];

/** A circle's radius. The outer circle's bend is negative and its radius is not. */
export function radiusOf(circle) {
  return 1 / Math.abs(circle.bend);
}

/**
 * How far a quadruple is from satisfying Descartes's relation. Zero for a real one; this
 * is the residual the tests hold every quadruple in the packing to.
 */
export function descartesResidual(bends) {
  if (bends.length !== 4) {
    throw new RangeError("Descartes's relation is about four circles");
  }
  const sum = bends.reduce((total, bend) => total + bend, 0);
  const squares = bends.reduce((total, bend) => total + bend * bend, 0);
  return sum * sum - 2 * squares;
}

/**
 * The two circles that fit the space left by three mutually tangent ones, as bends. The
 * smaller root is the circle that surrounds the three; the larger sits in the gap between
 * them.
 */
export function descartesBends(k1, k2, k3) {
  const inner = k1 * k2 + k2 * k3 + k3 * k1;
  if (inner < 0) {
    throw new RangeError(`${k1}, ${k2}, ${k3} are not three mutually tangent circles`);
  }
  const across = 2 * Math.sqrt(inner);
  return [k1 + k2 + k3 - across, k1 + k2 + k3 + across];
}

/**
 * Where the four starting circles sit, worked out from their bends rather than written
 * down. The outer circle is centred on the origin. The first inner circle is set against
 * it on the horizontal; the second is placed by the only two distances it is allowed —
 * from the outer circle's centre and from the first — and the third is what the complex
 * form of Descartes's relation returns for the three of them.
 *
 * Constructing it this way means the figure cannot begin from a quadruple that is merely
 * close to tangent, and the tests can hold the six tangencies of the root to the same
 * zero as every tangency the recurrence produces afterwards.
 */
export function rootCircles(bends = ROOT_BENDS) {
  if (descartesResidual(bends) !== 0) {
    throw new RangeError(`${bends.join(", ")} is not a Descartes quadruple`);
  }
  const [outerBend, firstBend, secondBend, thirdBend] = bends;
  const outerRadius = 1 / Math.abs(outerBend);
  const firstRadius = 1 / firstBend;
  const secondRadius = 1 / secondBend;

  const outer = { bend: outerBend, x: 0, y: 0 };
  const first = { bend: firstBend, x: outerRadius - firstRadius, y: 0 };

  // The second circle's centre is fixed by its two distances: from the origin, because it
  // is inside the outer circle and touching it, and from the first circle's centre.
  const fromOrigin = outerRadius - secondRadius;
  const alongTo = first.x;
  const x = (fromOrigin * fromOrigin + alongTo * alongTo
    - (firstRadius + secondRadius) * (firstRadius + secondRadius)) / (2 * alongTo);
  const second = {
    bend: secondBend,
    x,
    y: Math.sqrt(Math.max(0, fromOrigin * fromOrigin - x * x))
  };

  // And the third is the smaller of the two circles that fit against those three, which
  // the bend-weighted form of the same relation gives directly.
  const known = [outer, first, second];
  const weighted = (axis) => known.reduce((total, circle) => total + circle.bend * circle[axis], 0);
  const rootOf = (axis) => {
    const [a, b, c] = known;
    return a.bend * b.bend * a[axis] * b[axis]
      + b.bend * c.bend * b[axis] * c[axis]
      + c.bend * a.bend * c[axis] * a[axis];
  };
  const cross = known.reduce((total, circle, at) => {
    const next = known[(at + 1) % 3];
    return total + circle.bend * next.bend * (circle.x * next.y + circle.y * next.x);
  }, 0);
  // The square root is of a complex number, so it is taken in polar form.
  const realPart = rootOf("x") - rootOf("y");
  const magnitude = Math.hypot(realPart, cross);
  const rootReal = Math.sqrt((magnitude + realPart) / 2);
  const rootImaginary = Math.sign(cross || 1) * Math.sqrt((magnitude - realPart) / 2);
  const third = {
    bend: thirdBend,
    x: (weighted("x") - 2 * rootReal) / thirdBend,
    y: (weighted("y") - 2 * rootImaginary) / thirdBend
  };
  return [outer, first, second, third];
}

export const ROOT_CIRCLES = rootCircles();

/**
 * How far the packing is carried. Every gap holds another circle for ever, so the cutoff
 * is not a detail of the algorithm but a statement about the picture, and it is written
 * as one: a circle is kept when its radius is at least this fraction of the outer
 * circle's. The outer circle is drawn 306 logical pixels across the radius and the
 * picture is exported at twice that, so the smallest circle in the figure is one pixel
 * of the exported plate.
 */
export const FINEST_IN_OUTER_RADII = 1 / 612;

/**
 * The other circle of the pair, given a quadruple and which member to swap out. This is
 * Vieta on both the bend and the bend-weighted centre, so it is exact arithmetic on
 * whole numbers rather than a root taken twice.
 */
export function otherCircle(quadruple, index) {
  const swapped = quadruple[index];
  const rest = quadruple.filter((_, at) => at !== index);
  const bend = 2 * rest.reduce((total, circle) => total + circle.bend, 0) - swapped.bend;
  if (bend === 0) {
    throw new RangeError("the fourth circle of this quadruple is a straight line");
  }
  const weighted = (axis) =>
    2 * rest.reduce((total, circle) => total + circle.bend * circle[axis], 0)
    - swapped.bend * swapped[axis];
  return { bend, x: weighted("x") / bend, y: weighted("y") / bend };
}

/**
 * What makes two circles the same circle. Bends are whole numbers, and no two distinct
 * circles of this packing are anywhere near each other: the finest has a radius of about
 * three parts in ten thousand and the closest two centres are six parts in ten thousand
 * apart, so rounding centres to a millionth sits comfortably between the arithmetic's
 * own noise and any real distance.
 *
 * The rounding is the whole of it, and it is not cosmetic. The centres were once keyed
 * by `toFixed(9)`, and a circle whose centre landed on the axis from below came out at
 * y = -1.3e-15 and formatted as "-0.000000000" where its twin formatted as
 * "0.000000000". The two were taken for different circles and the packing carried one of
 * them twice, overlapping itself by two elevenths of the outer radius with nothing to
 * show for it, because the pair was drawn one on top of the other.
 */
const SAME_PLACE = 1e6;

function keyOf(circle) {
  const settled = (value) => Math.round(value * SAME_PLACE) / SAME_PLACE;
  return `${Math.round(circle.bend)}:${settled(circle.x)}:${settled(circle.y)}`;
}

/**
 * The packing, carried until every gap left would hold a circle finer than the cutoff.
 *
 * Quadruples are walked breadth first from the root, and each is asked for its four
 * neighbours. A neighbour past the cutoff is not followed, because every circle it would
 * lead to is smaller again — bends only grow as the gaps close.
 */
export function buildPacking(finest = FINEST_IN_OUTER_RADII) {
  const maxBend = Math.abs(ROOT_BENDS[0]) / finest;
  const circles = [];
  const seen = new Map();
  const remember = (circle, generation, parents) => {
    const key = keyOf(circle);
    if (seen.has(key)) {
      return seen.get(key);
    }
    const kept = { ...circle, generation, parents, index: circles.length };
    seen.set(key, kept);
    circles.push(kept);
    return kept;
  };

  // The root's four are each other's parents: any three of them decide the fourth.
  const root = ROOT_CIRCLES.map((circle, at) =>
    remember(circle, 0, [0, 1, 2, 3].filter((other) => other !== at)));
  let frontier = [root];
  let generation = 0;
  while (frontier.length > 0) {
    generation += 1;
    const next = [];
    for (const quadruple of frontier) {
      for (let index = 0; index < 4; index += 1) {
        const grown = otherCircle(quadruple, index);
        if (grown.bend > maxBend) {
          continue;
        }
        const key = keyOf(grown);
        if (seen.has(key)) {
          continue;
        }
        const kept = remember(
          grown,
          generation,
          quadruple.filter((_, at) => at !== index).map((circle) => circle.index)
        );
        next.push(quadruple.map((circle, at) => (at === index ? kept : circle)));
      }
    }
    frontier = next;
  }
  return circles;
}

/**
 * How far two circles are from touching: zero when they are tangent, positive when there
 * is room between them, negative when they overlap. The outer circle contains the rest,
 * so what touching means for it is that the gap closes on the inside.
 */
export function tangencyGap(first, second) {
  const apart = Math.hypot(first.x - second.x, first.y - second.y);
  if (first.bend < 0 || second.bend < 0) {
    const [outer, inner] = first.bend < 0 ? [first, second] : [second, first];
    return radiusOf(outer) - radiusOf(inner) - apart;
  }
  return apart - radiusOf(first) - radiusOf(second);
}

/** Whether two circles of the packing touch, to within the arithmetic's own noise. */
export function touching(first, second) {
  return Math.abs(tangencyGap(first, second)) < 1e-9;
}
